name: 'schema_processor'
description: 'A way to process the schemas for VS Code autocomplete'
version: '1.0.0'
publish_to: none
homepage: 'https://github.com/peiffer-innovations/flutter_json_schemas'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_class: '^2.1.6+1'
  yaon: '^1.1.0'

dev_dependencies:
  flutter_lints: '^2.0.1'
  test: '^1.23.1'

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
